version: "3"
services:
  tests:
    image: ${DOCKER_REGISTRY}milieuinfo/ubuntu-node:14
    command: bash -c "npm install && npm run test && tail -f /dev/null"
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      - HTTP_PROXY=${http_proxy}
      - HTTPS_PROXY=${https_proxy}
      - SKIP_WCT_SAUCE_POSTINSTALL_DOWNLOAD
      - NOSELENIUM
    extra_hosts:
      - "repository.milieuinfo.be:${REPOSITORY_FIXED_IP}"
    working_dir: /data
    volumes:
      - ${HOME:-.}/.npmrc:/root/.npmrc:ro
      - ${HOME:-.}/.gitconfig:/root/.gitconfig:ro
      - ${HOME:-.}/.git-credentials:/root/.git-credentials:ro
      - .:/data
